# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d18cfe020c829cdad1c58a5573fd9febb8d92d474c03085e18989886e5a41f4a505690ddb43712bb3a1f3984b49b3d78164453f324a3d671de2ab3f212367c4b

test:
  secret_key_base: 4ec4dce857ae4e10ae618e3ede9cd915358502c2da9e19f0c35d77b88e4ba9ad8ef7eb048dd02c22f9c5eec32ccac2f171aa6dbb5c40633780ed4d04c96ab140

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
